[package]
name = "ferros-core"
version = "0.0.0"
edition = "2021"
description = "Low-level debugging primitives and process control for Ferros."
license = "Apache-2.0"
repository = "https://github.com/jamallyons/ferros"
readme = "../../README.md"
keywords = ["debugger", "rust", "debugging", "ptrace"]
categories = ["development-tools"]

[dependencies]

[lints]
workspace = true
